[package]
name = "parrot-core"
version.workspace = true
edition.workspace = true

[dependencies]
parrot-protocol = { path = "../parrot-protocol" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
async-stream = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }